export interface Movie {
  title: string;
  originalTitle?: string;
  year: string;
  director: string;
  genre: string;
  description: string;
  reason: string; // Why AI recommended it
  posterUrl?: string; // Generated by AI
}

export interface QuizState {
  genre: string[];
  mood: string;
  era: string;
  company: string; // watching alone, friends, etc.
  extra: string;
}

export interface ChatMessage {
  role: 'user' | 'model';
  text: string;
}

export type AppView = 'intro' | 'quiz' | 'loading' | 'results';
